version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=app_db
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"